### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by deyemiobaa** [tylher/portfolio-site-skeleton#15]
Hello Taiwo, I cloned your repo to my computer and I noticed that your scripts don't load well on a regular browser. I had to install a live server on my editor before it could load correctly. 
My suggestion would be to add a description in your README file to inform others about this forehand.

Also, when I try to close the project pop-up it doesn't work and I noticed that you used a querySelector to get the item but you didn't add the dot to specify that it's a class. 
My suggestion would be to either use the getElementByClassName method or add a dot to the querySelector value

Cheers

**Comment by tylher** [comment]
Thank you @deyemiobaa  for the observation, I will look into the issue
